apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: <todo>
        ports:
        - containerPort: us-east4-docker.pkg.dev/qwiklabs-gcp-04-3089cb85bf93/my-repository/hello-cloudbuild-dev:v1.0
