apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-04-3089cb85bf93/my-repository/hello-cloudbuild-prod:v1.0
        ports:
        - containerPort: 8080
